const nodemailer = require('nodemailer');
const ejs = require('ejs');
const path = require('path');

// transporter is a part who sends the email
let transporter = nodemailer.createTransport({
    service: 'gmail',
    host: 'smtp.gmail.com',
    port: 587,
    secure: false,
    auth: {
        user: 'dhirajudhani870@gmail.com',
        pass: 'ieshffciovboasqs' // this is a hex code generated by 2 step verification in google which encrypt the password of user
    }
});

let renderTemplate = (data , relativePath) => {
    let mailHTML; // this make our email template nice using html
    ejs.renderFile(
        path.join(__dirname, '../views/mailers' , relativePath),
        data,
        function(err,template){
            if(err){
                console.log('Error in rendering template');
                return;
            }
            
            mailHTML = template;
            
        }
    )

    return mailHTML;
}

module.exports = {
    transporter: transporter,
    renderTemplate: renderTemplate

}